version: '3.9'
services:
  backend:
    container_name: ted_backend
    image: iotsharedcontainerregistry.azurecr.io/tedbackend:0.0.7
    ports:
      - '3000:3000'
    env_file:
      - .env
  frontend:
    container_name: ted_frontend
    image: iotsharedcontainerregistry.azurecr.io/tedwebapplication:0.0.4
    env_file:
      - .env
    ports:
      - '4200:4200'
