version: '3.9'
services:
  backend:
    container_name: ted_backend
    image: iotsharedcontainerregistry.azurecr.io/tedbackend:0.0.6
    ports:
      - '3000:3000'
    env_file:
      - .env
  frontend:
    container_name: ted_frontend
    image: iotsharedcontainerregistry.azurecr.io/tedwebapplication:0.0.1
    env_file:
      - .env
    ports:
      - '8080:80'
